- server/openapi_server/controllers/grant_controller.py
- server/openapi_server/dbmodels/grant.py
- server/openapi_server/test/integration/test_grant_controller.py
- server/openapi_server/test/integration/util.py
With this PR:
* `grant` dbmodel has been updated, e.g. adding a `grantId`, commenting out `sponsors` (for now)
* `grant` controllers added (create, get, list all, delete)
* tests for controllers added
> add specifications for grant (part 2)

- server/openapi_server/controllers/challenge_controller.py
- server/openapi_server/controllers/grant_controller.py
- server/openapi_server/dbmodels/base_document.py
- server/openapi_server/dbmodels/challenge.py
- server/openapi_server/test/integration/test_challenge_controller.py
- server/openapi_server/test/integration/util.py
With this PR:
* `challenge` dbmodel has been updated, e.g. adding a `challengeId`, commenting out grants and organizations (for now)
* `challenge` controllers added (create, get, list all, delete)
* tests for controllers added
> add specifications for challenge (part 3)

- server/openapi_server/models/challenge_results.py
- server/openapi_server/openapi/openapi.yaml
With this PR:
* ChallengeResults model will now include `nSubmissions` property
* specs will also include `nSubmissions` property
> update specs to include ChallengeResults.nSubmissions

- server/openapi_server/controllers/challenge_controller.py
- server/openapi_server/dbmodels/challenge_results.py
- server/openapi_server/test/integration/test_challenge_controller.py
- server/openapi_server/test/integration/util.py
Fix https://github.com/Sage-Bionetworks/rocc-client/issues/19
> Fix ChallengeResults

- .github/workflows/ci.yml
- .github/workflows/lock.yml
> Update CI workflow

- README.md
- server/openapi_server/dbmodels/challenge.py
- server/openapi_server/dbmodels/person.py
- server/openapi_server/dbmodels/tag.py
> Set required array as not required in Mongo models

- server/openapi_server/__main__.py
- server/openapi_server/controllers/challenge_controller.py
> Fix challenge filters

- .github/workflows/update.yml
- package.json
- server/openapi_server/models/date_range.py
- server/openapi_server/openapi/openapi.yaml
Implements https://github.com/Sage-Bionetworks/rocc-schemas/pull/140
> Update DateRange model

- server/openapi_server/models/date_range.py
- server/openapi_server/openapi/openapi.yaml
- server/openapi_server/test/__init__.py
Implements https://github.com/Sage-Bionetworks/rocc-schemas/pull/141
> Allow partial DateRange

- README.md
- docker-compose.yml
- package-lock.json
- package.json
- server/requirements.txt
> Prepare release 0.4.0

- .github/CONTRIBUTING.md
Mention the files where the project version must be updated.
> Update release doc

- server/openapi_server/controllers/challenge_controller.py
- server/openapi_server/dbmodels/challenge.py
- server/openapi_server/models/challenge.py
- server/openapi_server/models/challenge_create_request.py
- server/openapi_server/openapi/openapi.yaml
Related to https://github.com/Sage-Bionetworks/rocc-schemas/issues/158
> Add support for Challenge.doi

- server/openapi_server/dbmodels/org_membership.py
> Set orgid-userid unique for org memberships

- server/openapi_server/controllers/user_controller.py
- server/openapi_server/openapi/openapi.yaml
Related to https://github.com/Sage-Bionetworks/rocc-schemas/pull/173
> Get user orgs

- server/openapi_server/controllers/organization_controller.py
- server/openapi_server/dbmodels/organization.py
- server/openapi_server/models/organization.py
- server/openapi_server/models/organization_all_of.py
- server/openapi_server/models/organization_create_request.py
- server/openapi_server/openapi/openapi.yaml
Related to https://github.com/Sage-Bionetworks/rocc-schemas/pull/175
> Update org create request

- server/openapi_server/controllers/user_controller.py
- server/openapi_server/dbmodels/user.py
- server/openapi_server/models/user.py
- server/openapi_server/models/user_all_of.py
- server/openapi_server/models/user_create_request.py
- server/openapi_server/openapi/openapi.yaml
Related to https://github.com/Sage-Bionetworks/rocc-schemas/pull/178
> Add User.bio

- server/openapi_server/controllers/challenge_controller.py
> Return challenge stargazers

- server/openapi_server/controllers/challenge_controller.py
- server/openapi_server/dbmodels/challenge.py
Related to https://github.com/Sage-Bionetworks/rocc-app/pull/222
> Restore challenge search

- server/openapi_server/__main__.py
- server/openapi_server/controllers/challenge_controller.py
- server/openapi_server/openapi/openapi.yaml
Fixes #191 
Response:
```json
{
"challenges": [
{
"createdAt": "2021-10-28T22:38:19.077000Z",
"description": "This challenge is an awesome challenge.",
"displayName": "Kidney and Kidney Tumor Segmentation",
"endDate": "2021-09-17T00:00:00Z",
"fullName": "miccai/kidney-and-kidney-tumor-segmentation",
"id": "6166d00a014b66e55c8b044e",
"name": "kidney-and-kidney-tumor-segmentation",
"ownerId": "61664e84014b66e55c8ae8eb",
"platformId": "6166cfd8014b66e55c8b03eb",
"startDate": "2021-08-23T00:00:00Z",
"status": "completed",
"topics": [
"kits21",
"kidney",
"kidney-tumor",
"segmentation"
],
"updatedAt": "2021-10-28T22:38:19.077000Z",
"websiteUrl": "https://kits21.kits-challenge.org/"
},
{
"createdAt": "2021-10-28T22:38:19.077000Z",
"description": "This challenge is an awesome challenge.", …
```
> Filter org challenge search terms

- server/openapi_server/controllers/challenge_controller.py
- server/openapi_server/dbmodels/challenge.py
- server/openapi_server/dbmodels/challenge_readme.py
- server/openapi_server/models/challenge.py
- server/openapi_server/models/challenge_all_of.py
- server/openapi_server/openapi/openapi.yaml
Implements https://github.com/Sage-Bionetworks/rocc-schemas/pull/201
> Add support for Challenge.readmeId

- server/openapi_server/openapi/openapi.yaml
Implements https://github.com/Sage-Bionetworks/rocc-schemas/pull/203
> Remove remaining references to `tags`
